name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master,develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      - name: Download and extract SonarQube
  uses: actions/download-artifact@v2
  with:
    name: sonarqube
    path: /tmp/sonarqube.tar.gz

- name: Extract SonarQube
  uses: actions/extract-archive@v2
  with:
    archive-path: /tmp/sonarqube.tar.gz
    destination: /opt/sonarqube

