name: SonarQube Scan

on: [push]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
- name: Download and extract SonarQube
  uses: actions/download-artifact@v2
  with:
    name: sonarqube
    path: /tmp/sonarqube.tar.gz

- name: Extract SonarQube
  uses: actions/extract-archive@v2
  with:
    archive-path: /tmp/sonarqube.tar.gz
    destination: /opt/sonarqube
- name: Start SonarQube
  uses: actions/runner@v2
  with:
    working-directory: /opt/sonarqube/bin/linux-x86-64
    args: ./sonar.sh start
